feature(Jwt): Make cookie from jwtFilter conditional
SymphonyPlatformSolutions/symphony-bdk-bot-sdk-java pull request #91
Opened 2020-09-04 20:17 UTC by gluizbr

2020-09-05 09:27 UTC, symphony-thibault commented
Hi @gluizbr - This repository is actually deprecated and has been moved to https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/tree/master/symphony-bdk-legacy/symphony-bdk-bot-sdk-java

2020-09-08 12:20 UTC, marcus-secato-symphony approved these changes

2020-09-08 13:25 UTC, symphony-thibault requested changes
As mentioned in this project `README`, we moved the actual codebase to https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/tree/master/symphony-bdk-legacy/symphony-bdk-bot-sdk-java. 

@symphony-elias Could we close this repo?

2020-09-08 13:55 UTC, gluizbr commented
> As mentioned in this project `README`, we moved the actual codebase to https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/tree/master/symphony-bdk-legacy/symphony-bdk-bot-sdk-java.
> 
> @symphony-elias Could we close this repo?

Sorry about that, opened an PR on the correct repo
https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/203

2020-09-08 13:55 UTC, closed without merging